### ISSUE TITLE
add-password, set-password, delete-password issues

### ISSUE THREAD

**Issue by blackjackshellac** [Keruspe/GPaste#207] opened 2017-04-08 12:38 UTC
I added a password using the cli and then used set-password to change its position in the list but discovered that it duplicated it instead of moving it.  Does the password entry exist independent of the history?  Is it stored securely?

```
$ gpaste-client add-password foo bar
$ gpaste-client set-password 5 foo
$ gpaste-client | grep foo
0: [Password] foo
5: [Password] foo
```

Should deleting a named password also remove it completely from the history?

```
$ gpaste-client delete-password foo
$ gpaste-client | grep foo
4: [Password] foo
```

Finally, searching for the password by name in the extension does not find it.

```
$ gpaste-client version
GPaste 3.22.3
```

**Comment by Keruspe** [comment] 2017-04-11 08:25
So, let's sum things up.

First, add-password. When you add a password with the name "foo", a `delete-password foo` is hooked before so that there is only one password named foo in history.

Second, delete-password. When you delete the password with the name "foo", it only deletes the first one it finds as there's supposed to be only one in the history with that name.

Third, set-password. set-password converts an already existing item as a password with a given name. That's where the bug is located. When you set-password with the name "foo", there is no check of whether there's already a password with that name or not.

Now, let's say you have a password named "foo" in position 3, and you "set-password 5 foo". Should the password at position 3 remain inchanged and the item in position 5 be deleted as they both are "the foo password" and item 3 is more recent? Or should item 3 be deleted because the action of making 5 a password is more recent?

Not sure which make more sense. Second possibility is easier as it's just a matter of hooking a delete-password like for add-password

**Comment by blackjackshellac** [comment] 2017-04-11 12:39
Not sure that duplication in the list is ever beneficial, can't think of any reason off the top of my head at least.  I'd suggest move rather than copy.

**Comment by Keruspe** [comment] 2017-04-11 12:46
I think there is some confusion here, there's no copy nor move and there won't be either once the issue is fixed.
set-password converts an existing item as a password, it doesn't move or copy a password to some destination.

Imagine this scenario: I have two gmail accounts. First one is "foo", with password "test", second one is "bar" with password "waldo".
Now let's say that I only name them "gmail" with no differentiation whatsoever.

If the 3rd element in history is a password, named "gmail" and containing "waldo", the password from my second gmail account, and the 5th element is a clear text item containing "test", the password from my first gmail account. Let's say I want to convert that 5th item as a password, named gmail like the 3rd one.
`gpaste-client set-password 5 gmail`
Now there are two passwords named gmail in the history, which is a situation that we want to avoid. Which one do we want to keep and which one do we want to delete? Do we keep "waldo" as it's the more recent one or do we keep "test" as it's the one we just marked as being a password?

**Comment by blackjackshellac** [comment] 2017-04-11 14:15
Yeah, I was a little confused about the meaning of set-password, initially I was trying to use "add-password" to paste an existing clipboard password into a named password but this wouldn't work because the password text was already in the list, but that's another issue.  Perhaps it would be possible to convert the existing entry into a password in that scenario?

As for your scenario, I would say that the existing password should take priority when trying to set the second it should fail with the message that the named password already exists and/or non-zero exit status.

**Comment by Keruspe** [comment] 2017-04-11 14:17
Makes sense.

**Comment by Keruspe** [comment] 2017-04-11 14:31
The first part of your last message is now fixed, I'll do a release soon-ish, when I've fixed the second part

**Comment by Keruspe** [comment] 2017-04-11 15:16
Second part should now be fixed too. i'll release tomorrow

**Closed by Keruspe** 2017-04-11 15:16 UTC
Labels: BUG
