### ISSUE TITLE
gpaste-daemon gets stuck

### ISSUE THREAD

**Issue by slune** [Keruspe/GPaste#151] opened 2016-05-04 22:31 UTC
Hi,

After a specific paste(I do not know exactly which one) gpaste daemon get stuck with this message:

(gpaste-daemon:12652): GLib-CRITICAL **: g_main_loop_quit: assertion 'loop != NULL' failed

Strace:
[gpaste_strace.txt](https://github.com/Keruspe/GPaste/files/249696/gpaste_strace.txt)

I have to kill -9 the process to restart it.
Fedora 23

gpaste-libs-3.18.3-1.fc23.x86_64
gpaste-3.18.3-1.fc23.x86_64

**Comment by Keruspe** [comment] 2016-05-06 08:08
Are you able to reproduce on demand?
Do you have any more logs somewhere? Any change you could get a gdb backtrace?

**Comment by slune** [comment] 2016-05-10 20:11
I am not able to reproduce it on demand.

What is the right way how to run it in a debug mode?

I'll try to get gdb when it happens next.

**Comment by slune** [comment] 2016-05-11 22:43
I do not thing it's connected to a specific copy. I tried a bunch of lines just after it stopped working and it did not get stuck. I started seeing this behavior only in the last 2 new releases (I think). 

back trace from gdb:
[gpaste_bt.txt](https://github.com/Keruspe/GPaste/files/260343/gpaste_bt.txt)

I am do not know how to enable more logging for the daemon. If you need more data let me know.

Thanks!

**Comment by Keruspe** [comment] 2016-05-12 08:11
You can locate whene the daemon is installed on you system, kill the already running one and launch it by hand

G_MESSAGES_DEBUG=all /usr/libexec/gpaste/gpaste-daemon

or something like that.

Thanks for the stack, will look into it asap, as I'm eager to do a release with other fix and want to get this fixed before

**Comment by Keruspe** [comment] 2016-05-13 13:50
Is the stacktrace always the same when this happens?

I can't seem to find anything wrong in what GPaste is doing there and it looks like it's gtk+ hanging

**Comment by slune** [comment] 2016-05-18 17:36
This is the next back trace:
[gpaste_bt_20160518.txt](https://github.com/Keruspe/GPaste/files/271039/gpaste_bt_20160518.txt)

G_MESSAGES_DEBUG=all /usr/libexec/gpaste/gpaste-daemon

did not help - I still do not see any logging except:
(gpaste-daemon:30277): Gtk-DEBUG: Connecting to session manager
(gpaste-daemon:30277): GLib-CRITICAL **: g_main_loop_quit: assertion 'loop != NULL' failed

Is there anything else I can do to help with debug?

**Comment by Keruspe** [comment] 2016-05-18 20:11
I'll do a release hopefully within a few days with more debug logs, and making this action async.
We'll see if things get better then.

**Comment by Keruspe** [comment] 2016-05-18 20:20
I'm really starting to think that this is a bug in gtk+ though

**Comment by Keruspe** [comment] 2016-05-18 20:48
If you still hit the problem with next release, please reopen

**Comment by slune** [comment] 2016-07-01 18:15
Having the same problem on F24:
gpaste-3.20.3-2.fc24.x86_64

**Comment by Keruspe** [comment] 2016-07-02 18:01
@slune can you try running with G_MESSAGES_DEBUG=all as before? I added some debugging logs since you last try with that

**Comment by slune** [comment] 2016-07-09 03:16
even if I run it like with it I get:

~]$ G_MESSAGES_DEBUG=all;/usr/libexec/gpaste/gpaste-daemon

(gpaste-daemon:27315): GLib-CRITICAL **: g_main_loop_quit: assertion 'loop != NULL' failed

There is one change though - I am able to ctrl c from it - I do not have to kill -9 it.
Am I the only one who experience this?

**Comment by Keruspe** [comment] 2016-07-09 07:56
Running it with G_MESSAGES_DEBUG=all isn't supposed to solve the problem. It's supposed to produce more verbose output so that you can paste it there so that I get more context around the failure.
Not pasting the output renders it useless.

I never heard of anyone else but you hitting that, that's why I'd love to get the output with debug logs to further investigate.

**Comment by slune** [comment] 2016-07-10 02:24
yup, I know I did not get any output except 
(gpaste-daemon:27315): GLib-CRITICAL **: g_main_loop_quit: assertion 'loop != NULL' failed

I am wandering if I am not using it wrong. 

I run it like this:
G_MESSAGES_DEBUG=all;/usr/libexec/gpaste/gpaste-daemon

**Comment by Keruspe** [comment] 2016-07-10 06:35
Ah, didn't notice.
You need to run G_MESSAGES_DEBUG=all /usr/libexec/gpaste/gpaste-daemon

**Comment by slune** [comment] 2016-07-12 21:26
This is what I got:
[gpaste.txt](https://github.com/Keruspe/GPaste/files/360283/gpaste.txt)

I cannot see anything interesting in logs. 
I can see the daemon is still gets data when I do ctrl+c.
I can see the data in UI.
And they are in the clipboard.
But when I select another item from UI: 
I can see the selection in the log, but it doesn't change the clipboard itself.

Is it the description clear?

**Comment by slune** [comment] 2016-07-13 02:54
one more:

(gpaste-daemon:16732): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:16732): GPaste-DEBUG: clipboards-manager: notify finish

(gpaste-daemon:16732): GLib-CRITICAL **: g_main_loop_quit: assertion 'loop != NULL' failed
(gpaste-daemon:16732): GPaste-DEBUG: PRIMARY: store
(gpaste-daemon:16732): GPaste-DEBUG: PRIMARY: owner change
(gpaste-daemon:16732): GPaste-DEBUG: clipboards-manager: notify

**Comment by Keruspe** [comment] 2016-09-18 07:52
Ok, this should be fixed in git now.
I totally dropped the gtk_clipboard_store call as it doesn't makes sense in GPaste anyway.

Fix will be part of the 3.22 release

**Closed by Keruspe** 2016-09-18 07:52 UTC
