### ISSUE TITLE
gnome-shell-extension-gpaste occasionally crashes

### ISSUE THREAD

**Issue by mvuets** [Keruspe/GPaste#112] opened 2015-03-04 15:20 UTC
I have two laptops, both run Fedora 21 workstation (though one got an install from scratch, another was upgraded from F20). Both run stock vanilla GNOME 3 with a few shell extensions. And on one laptop I constantly experience problems with the GPaste shell extension.

Occasionally (after an hour or two) a GPaste icon would disappear from the top bar and the extension would be completely gone. The gpaste deamon seems to keep running fine (`gpaste` spits out the history). Neither `gpaste daemon-reexec`, nor "turn it off and on again in `gnome-tweak-tool`" seem to resurrect it.

I know this description does not give much insight. But I feel rather lost in this modern monstrous desktop environments and don't even know where to start debugging the problem. I love the extension (much better than clipit or parcellite)!.. and if you could tell me how I can provide you with more meaningful and useful data, I'd be happy to do that (-:

For starters:

```
$ cat /etc/system-release
Fedora release 21 (Twenty One)
$ uname -i
x86_64
$ yum info gnome-shell-extension-gpaste gpaste | grep 'Name\|Version\|Release'
Name        : gnome-shell-extension-gpaste
Version     : 3.14.1
Release     : 1.fc21
Name        : gpaste
Version     : 3.14.1
Release     : 1.fc21
```

**Comment by Keruspe** [comment] 2015-03-04 15:26
Hi,

Which version of gnome-shell are you running?
Also, when the problems appears, does `journalctl /usr/bin/gnome-session` give your more information like some stacktrace?

Thanks for reporting, I fear I already know of this issue, as it could be the same as #106 

What other extensions do you have installed btw, let me find another closed issue back, I think someone had troubles because of another extension doing silly things

**Comment by Keruspe** [comment] 2015-03-04 15:28
Here is the other issue I thought of: #51

**Comment by mvuets** [comment] 2015-03-04 15:51
Hi, thanks for the quick reaction!

My current `journalctl` output looks rather clobbered at the moment. I'll start from scratch next time and send you the relevant bit.

I am running gnome-shell version 3.14.3. Other shell extensions in use (not much):
- https://git.gnome.org/browse/gnome-shell-extensions
  - Native window placement
  - Removable drive menu
- Pomodoro, https://github.com/codito/gnome-shell-pomodoro

**Comment by mvuets** [comment] 2015-03-05 17:23
Ha, finally caught the crash! I think the extension crashed right after the pomodoro was up (it dims out the screen and run a break countdown). 

The relevant piece of `journalctl /usr/bin/gnome-session`:
```
Mar 05 18:19:13 ocean gnome-session[2981]: (gnome-shell:3113): GLib-GObject-WARNING **: gsignal.c:2579: instance '0x7fae4b0' has no handler with id '560027'
Mar 05 18:19:13 ocean gnome-session[2981]: (gnome-shell:3113): Gjs-WARNING **: JS ERROR: Error: Type name Gjs_GPasteAboutItem is already registered
Mar 05 18:19:13 ocean gnome-session[2981]: GObjectMeta<._construct@resource:///org/gnome/gjs/modules/overrides/GObject.js:125
Mar 05 18:19:13 ocean gnome-session[2981]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Mar 05 18:19:13 ocean gnome-session[2981]: Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/lang.js:204
Mar 05 18:19:13 ocean gnome-session[2981]: Class@resource:///org/gnome/gjs/modules/lang.js:152
Mar 05 18:19:13 ocean gnome-session[2981]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/aboutItem.js:29
Mar 05 18:19:13 ocean gnome-session[2981]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/indicator.js:36
Mar 05 18:19:13 ocean gnome-session[2981]: @/usr/share/gnome-shell/extensions/GPaste@gnome-shell-extensions.gnome.org/extension.js:28
Mar 05 18:19:13 ocean gnome-session[2981]: initExtension@resource:///org/gnome/shell/ui/extensionSystem.js:220
Mar 05 18:19:13 ocean gnome-session[2981]: enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:109
Mar 05 18:19:13 ocean gnome-session[2981]: _onVersionValidationChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:284
Mar 05 18:19:13 ocean gnome-session[2981]: _onVersionValidationChanged@resource:///org/gnome/shell/ui/extensionSystem.js:283
Mar 05 18:19:14 ocean gnome-session[2981]: (gnome-shell:3113): GLib-CRITICAL **: Source ID 204034 was not found when attempting to remove it
```

Does it give any hope? (-:

**Comment by Keruspe** [comment] 2015-03-06 07:50
Ok, that's exactly the one I suspected, thanks for the info.
I'll try harder to reproduce but at the moment I still suspect gnome-shell and/or gjs to do weird stuff.

Closing as duplicate of issue #106 though

**Closed by Keruspe** 2015-03-06 07:50 UTC

**Comment by mvuets** [comment] 2015-03-06 08:00
Subscribed to #106, thanks for investigating!

Have you tried to file a bug against gnome-shell, maybe? Have you got enough evidence?

**Comment by Keruspe** [comment] 2015-03-06 08:02
I have no evidence, just a huge suspicion :/

**Comment by mvuets** [comment] 2015-03-06 09:38
By the way, maybe you know how can I mitigate the problem for the time being? Can I resurrect the extension without loggin-out/-in? (Having to restart all apps sucks) )-:

**Comment by Keruspe** [comment] 2015-03-06 13:31
alt-f2  r   should do the trick

**Comment by mvuets** [comment] 2015-03-06 14:41
Wow, that indeed helped! Did not know the trick, thanks a lot.

**Comment by Keruspe** [comment] 2015-03-06 23:23
Fyi, I finally managed to track it down.
It's definitely a bug in gjs but I found a way to bypass it in GPaste.
Will do a 3.14.x this week end I hope.
