### ISSUE TITLE
copy/paste and content-type text/html

### ISSUE THREAD

**Issue by kapouer** [Keruspe/GPaste#176] opened 2016-10-17 14:24 UTC
Hi,
1. copy html from a contenteditable node in a chromium web page,
   typically, use the [prosemirror demo](http://prosemirror.net/)
2. paste it in the contenteditable node: markup is kept
3. select another item from gpaste history, then select the copied html again
4. paste it again in the same place: markup disappeared

It would be nice if gpaste didn't strip markup. I suspect this is a problem with
content-type text/html not being carried somewhere.

**Comment by Keruspe** [comment] 2016-10-18 09:37
Hi,

Yep, what's happening here actually is that GPaste doesn't support rich text, but downgrades it to text.
I remember looking into rich text a looooong time ago and can't recall why this wasn't handled or why it was removed.
I'll add that to the next version, tanks for the reminder !

**Comment by Keruspe** [comment] 2017-02-13 13:26
FYI, I have some rework of the mime types handling locally that eventually will fix that.
The current state is worth than before right now, but once I'll have it finished I'll push it and it should work.

**Comment by Keruspe** [comment] 2017-02-13 16:12
This is not as easy as it sound actually.
Adding a special case for text/html would we easy enough, but having something more "flexible" will be a lot more greedy.

When you select something in firefox, it advertises that something compatible with text/plain, string, utf8-string [...] and text/html has been selected.

When you request it as text/html, it gives you the html, when you request it as stirng, it gives you a stripped down version with only the text and not the html tags.
Handling this specific case would be easy, i'd just have to store both values and return the one asked for afterwards, but doing something more flexible would mean requesting the data for each type (which are called targets) that it advertises and store the couple target <-> value. That owuld mean asking for the data like 7 or 8 times for firefox, but could be far worse with other software I guess

**Comment by kapouer** [comment] 2017-02-13 20:37
> That would mean asking for the data like 7 or 8 times for firefox, but could be far worse with other software I guess
i disagree with this - my guess is that most software supports only one or two formats - as it asks developers to actively add support for new formats. The worst case should be web browsers.
I didn't know clipboard was doing content negotiation like http servers, but it makes sense.

**Comment by Keruspe** [comment] 2017-02-13 21:59
firefox only adds text/html, the other ones are just sort of aliases of text/plain that are advertised by at least every gtk application when you select text.

My bet for the worst case would be on IDE.

I think I'm gonna add a new configuration key, in the form of a list of extra text mimetypes to handle, defaulting to ["text/html"]. I guess that would be a good compromise.

**Comment by Keruspe** [comment] 2017-03-15 14:51
Ok, I just made half the work to get it to work (the sending part) and will do the receiving/storing part in the next days so that'll be in 3.24

**Comment by Keruspe** [comment] 2017-04-05 15:51
This is way less trivial that it seems. Actually, it's even way more complicated than I thought at the beginning.
When you go out of the "standard" mime types imposed by X, and you start using things such as text/html, you can basically provide any data you want. So while there are several text targets for unicode handling in basic text, applications can send out whatever they want for text/html.
Firefox, for example, sends utf8 for plain text, and utf16 for text/html *for the same copy action*.

I'm at a point where things start to really work well with firefox, but then it doesn't with chromium.

I'll probably release 3.24 soon without this, and defer all that until I find out how exactly I can detect the right contents

**Comment by Keruspe** [comment] 2017-04-06 07:53
Well, actually, since everything else was ready, a simple workaround was to just use base64 instead of trying to get everything as utf8: https://github.com/Keruspe/GPaste/commit/b623586355161b0ba9f77219d232eb4791472644

Closing now as it works! I'll poke around for regression checking and release should come pretty soon

**Closed by Keruspe** 2017-04-06 07:53 UTC
Labels: RFE

**Comment by kapouer** [comment] 2017-04-06 08:01
Looks very cool, but with debian near release, i won't be able to test it on gnome 3.24 before some time.

**Comment by Keruspe** [comment] 2017-04-06 08:46
Yup, the release was slightly delayed due to the family growing and the spare time decreasing
