### ISSUE TITLE
Breaks clipboard on GNOME Shell Wayland session

### ISSUE THREAD

**Issue by pothos** [Keruspe/GPaste#240] opened 2018-04-19 06:56 UTC
If used with the GNOME Shell Wayland session, certain applications like Epiphany or others after longer time can't copy anymore (track-changes on, track-extension-state on, primary-to-history off, synchronize-clipboards off).

**Comment by pothos** [comment] 2018-04-19 07:10
The intervall tracking method of https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/ does not have this problem.

**Comment by Keruspe** [comment] 2018-04-19 09:02
That's weird, I've been running the gnome-shell wayand session for maybe 4 years or so now, and didn't hit this issue.
Is there a way to reliably reproduce?

**Comment by pothos** [comment] 2018-04-19 10:11
Epiphany (GNOME Web) ist the most reliable candidate to give up on copying.

**Comment by pothos** [comment] 2018-04-19 10:14
It also seems that a crash in GNOME Shell can be trigged with it, so there might be a connection of both issues: https://gitlab.gnome.org/GNOME/mutter/issues/69

**Comment by Keruspe** [comment] 2018-04-19 21:04
Oh, I've seen some crashes like this !
It's interresting because GPaste only interacts with X11 using the GtkClipboard API, so there might be either:
- a bug in mutter's handling of X11 clipboards events (maybe a race ?)
- a bug in the GtkClipboard's interaction with X11
- a bug in GPaste's interaction with GtkClipboard

In some scenarios, GPaste might be a bit too eager in changing the ownership of some selection, that might maybe cause some race inside of mutter's wayland<->x11 clipboard sync?

Can you reproduce inside of an X11 session?

**Comment by pothos** [comment] 2018-04-20 02:57
With the X session there were never those problems from my experience. But yes, it seems to be tricky to debug - do you have an eye on your session logs? I remember seeing some failed read events with journalctl, but my logs are gone now.

**Comment by kapouer** [comment] 2019-04-30 13:47
Still happening on xwayland / gnome-shell 3.32 / mutter 4 / gpaste 3.32 using debian experimental here.

**Comment by Keruspe** [comment] 2020-12-22 20:59
This was fixed in mutter 3.38 AFAIK

**Closed by Keruspe** 2020-12-22 20:59 UTC
Labels: BUG
