### ISSUE TITLE
Only one item in history (ie: Gpaste doesn't keep history anymore)

### ISSUE THREAD

**Issue by axelsimon** [Keruspe/GPaste#365] opened 2021-09-16 15:00 UTC
I recently upgraded to Fedora 34 and i discovered that my Gpaste history is empty, save for one item: the last thing copied.

It appears that Gpaste 3.40.2 only keeps the last item in history, even though my history is currently set at 200 items.

Screenshot of Gpaste:
![Screenshot from 2021-09-16 15-59-26](https://user-images.githubusercontent.com/1172256/133635996-7112b632-2bcd-4ebc-87be-1fa63fb87df6.png)

Is this a known issue? I couldn't find any other issue mentioning the same problem.

Happy to try and provide further info.

**Comment by axelsimon** [comment] 2021-09-17 10:35
Well this is strange, my history simply started working again a few hours after i created this issue. I will close it.

**Comment by axelsimon** [comment] 2021-12-08 15:48
@Keruspe I'm reopening this, as it's still an issue.
I'm still regularly discovering my clipboard history reduced to one item, with all other items lost (which is pretty bad, given once you have a clipboard manager, you start relying on it to remember things for you temporarily). And, as described in the original, when the problem happens, the history in gpaste is capped at 1 item.

My solution so far is just `pkill gpaste-daemon` followed by `gpaste-client` but @sferra's option seems like the same thing but qiucker and cleaner, so i'll try that next time.

**Comment by baurmatt** [comment] 2022-03-08 10:15
Just wanted to report that I'm experiencing the same issues since ~6 months on Arch Linux. Currently running gpaste 3.42.6-1 on Gnome 41.3-1. My workaround is to `killall gpaste-daemon` and restart the app. It seems to me that this issue happens after my laptop comes back from suspend, but that's just a hunch right now.

**Comment by Keruspe** [comment] 2022-03-08 11:08
Did you see it happen with 3.42.6 too?
Any logs in the journal?

**Comment by baurmatt** [comment] 2022-03-08 12:09
> Did you see it happen with 3.42.6 too?

I guess this goes out to @axelsimon and @sferra :)

> Any logs in the journal?

Nothing interesting:
``` 
$ journalctl --since today | grep gpaste
Mär 08 11:11:10 T14s gpaste-daemon[2040]: Stop signal received, exiting
```

**Comment by Keruspe** [comment] 2022-03-08 12:25
On Tue 8 Mar 2022 at 13:09, Matthias Baur ***@***.***> wrote:

> Did you see it happen with 3.42.6 too?
>
> I guess this goes out to @axelsimon <https://github.com/axelsimon> and
> @sferra <https://github.com/sferra> :)
>

No, this was for you, you’ve seen it with 3.42.6 running?


Any logs in the journal?

**Comment by baurmatt** [comment] 2022-03-08 12:44
Yes, I've experienced it this morning with 3.42.6. I couldn't find anything interesting in journald which matched the search term `gpaste`

**Comment by Keruspe** [comment] 2022-03-08 12:56
Does coredumpctl list anything?

**Comment by baurmatt** [comment] 2022-03-08 13:08
Nope, nothing that matches `gpaste`.

**Comment by baurmatt** [comment] 2022-03-27 12:19
I suspect for a while that this problem happens after updates of dependencies are installed and the computer/service isn't restarted. Today I ran into the problem again and check the updates I've installed last night:

gtk3 (1:3.24.33-1 -> 1:3.24.33-2)
gnome-shell (1:41.4-1 -> 1:41.5-1)
gobject-introspection-runtime (1.70.0-5 -> 1.72.0-1)

Those are the [dependencies of gpaste](https://archlinux.org/packages/extra/x86_64/gpaste/) which had updates installed. Does this make any sense?

Any idea how I'm supposed to debug this when it is currently happening?

**Comment by olivergondza** [comment] 2022-04-20 10:40
I observe this sporadically on Arch Linux with 3.42.6. `gpaste-client daemon-reexec` do fix it. I found no recent/relevant coredumps, nothing relevant in journal either. However, I have not updated any dependency since the last reboot, and this problem appeared anyway. This is happening on wayland.

Is there a way I can collect more input?

**Comment by olivergondza** [comment] 2022-04-20 10:40
I observe this sporadically on Arch Linux with 3.42.6. `gpaste-client daemon-reexec` do fix it. I found no recent/relevant coredumps, nothing relevant in journal either. However, I have not updated any dependency since the last reboot, and this problem appeared anyway. This is happening on wayland.

Is there a way I can collect more input?

**Comment by joewilliams** [comment] 2022-05-08 18:12
I am having the same problem on ubuntu 21.04 and gpaste 3.42.6.

**Comment by rbjorklin** [comment] 2022-09-02 16:59
This seems like a duplicate of #354, is that correct?

**Comment by sferra** [comment] 2022-09-02 18:47
> This seems like a duplicate of #354, is that correct?

Yes, it looks like the same issue.

**Comment by axelsimon** [comment] 2022-10-10 14:57
I just checked what `journalctl --since today | grep gpaste` returns, having just run into the issue again, and i get tens of lines of:
```Oct 10 12:04:16 laptop gpaste-daemon[882551]: g_paste_history_private_check_memory_usage: assertion 'biggest' failed```

It seems to be a different issue then?

**Comment by Keruspe** [comment] 2022-10-11 08:13
You just might have found something, thanks!

**Comment by dumbasPL** [comment] 2022-10-11 09:55
Can confirm, I also have my journal spanned with the same exact error message.

**Comment by Keruspe** [comment] 2022-10-11 12:07
Ok, I'm pretty sure now that I know exactly what is going on and I have a local fix.

When detecting a growing line and the active item is the biggest in history, we hit this problem.

**Comment by fkr-0** [comment] 2022-11-25 08:13
Hey I recently built from Master (cad0e45dfa3e56bbe5e7467496a429017876bf74) and hit the problem again, I think:

```
Nov 24 00:09:55 sys gpaste-daemon[1697]: g_paste_history_private_check_memory_usage: assertion 'biggest' failed
Nov 24 00:10:03 sys gpaste-daemon[1697]: g_paste_history_private_check_memory_usage: assertion 'biggest' failed
```
if I can help clarifying the issue please let me know. And thanks for the great software.

**Comment by Keruspe** [comment] 2022-11-25 09:08
Thanks, will give it yet another thorough look and try and make a release too.

Just checking : you're 100% sure you were running the daemon built from master and not the one from your system when this happened right? DBus activation can easily trick you with this if you don't manually start the daemon

**Comment by fkr-0** [comment] 2022-12-09 09:06
yes, i can confirm that it is still happening
```

Dec 05 22:35:39 sys gpaste-daemon[2662916]: g_paste_history_private_check_memory_usage: assertion 'biggest' failed
Dec 05 22:35:39 sys gpaste-daemon[2662916]: g_paste_history_private_check_memory_usage: assertion 'biggest' failed
Dec 05 22:35:46 sys gpaste-daemon[2662916]: g_paste_history_private_check_memory_usage: assertion 'biggest' failed
Dec 05 22:36:12 sys gpaste-daemon[2662916]: g_paste_history_private_check_memory_usage: assertion 'biggest' failed
Dec 05 22:37:15 sys gpaste-daemon[2662916]: g_paste_history_private_check_memory_usage: assertion 'biggest' failed
```

**Comment by levihb** [comment] 2023-02-19 07:06
Just wanted to say that this is still happening regularly for me. I don't know what it is, sometimes I'll open it and it'll have a single item, then other times I'll open it, and it'll be working fine.

E.g. at the moment it's broken for some reason. No I have not updated any dependencies since I turned the system on. And I'm completely missing the errors people here posted.

If someone has a workaround or similar that'd be great. Because this is severely disrupting my workflow to the point where I'm just considering giving up on it. If there's anyway I can help please do tell me.

**Comment by Keruspe** [comment] 2023-02-19 07:24
What is the output of ‘gpaste-client daemon-version’ ?
Do you have any logs of when this happens?

**Comment by stolyarchuk** [comment] 2023-02-19 13:39
Having the same problem after suspending and resuming on my latest Fedora system. It  appears randomly, not after every resuming. Solved it with restarting gpaste systemd user service after PC been resumed.

**Comment by levihb** [comment] 2023-02-21 11:18
@Keruspe Version 43.1. No logs that I can see.

I can't figure out the cause or certain - but I'm fairly sure it's the same as @stolyarchuk. When coming out of sleep mode for some reason it just shows a single history item, whatever is currently on the clipboard.

**Comment by Keruspe** [comment] 2023-02-21 11:28
Not sure what could cause this yet, but that's definitely a lead. I'll try to reproduce on my end. Logs would help though until I can reproduce

**Comment by stolyarchuk** [comment] 2023-02-21 11:36
i'm using this systemd service as a workaround
```
[Unit]
Description=Restart GPaste after resume from sleep/suspend
After=suspend.target

[Service]
Type=oneshot
ExecStart=/usr/bin/systemctl --machine your_username_here@.host --user restart org.gnome.GPaste.service

[Install]
WantedBy=suspend.target
```
hope this could help someone before @Keruspe find the solution

**Comment by bobi32** [comment] 2023-03-20 08:35
So, wanting to investigate the journal entry, I kept a debugger open for a few days until the issue triggers again the call to g_return_if_fail(biggest) in gpaste-history.c::g_paste_history_private_check_memory_usage

It turns out it happens while my history is full and starting to discard old entries when adding new ones. With first investigations when it first happens biggest is NULL, leading me to think the entry matching the priv->biggest_uuid has been discarded, thus resolved to NULL by the **_get_item_by_uuid call.

The trick is, this keeps happening afterwards (the whole biggest being resolved to NULL hence the g_return_if_fail triggered) whenever I copy some new stuff; the history is not yet broken atm though (but I am pretty sure it will be eventually)

I cannot pretend I understand plainly how gpaste works, but my two cents are that a new biggest entry might be looked for whenever priv->biggest_uuid turn out stale.

**Closed** 2023-03-20 13:43 UTC

**Comment by batiukmaks** [comment] 2023-04-10 14:38
> 

Hello!
For several weeks this command line helps me to restart the GPaste. But I am annoyed of it, how can I make my GPaste work forever?

**Comment by Keruspe** [comment] 2023-04-10 14:55
Which version are you running ? Should be ok if it's up to date

**Comment by bobi32** [comment] 2023-04-20 11:48
Even with the latest build the issue seems unfixed. With more tests I came up with a repeatable use case:

- For a history of 100 with this file [history.xml.gz](https://github.com/Keruspe/GPaste/files/11285459/history.xml.gz)
1. Stop GPaste daemon: `systemctl --user stop org.gnome.GPaste.service`
2. Replace history:  `gzip -cd > ~/.local/share/GPaste/history.xml`
3. Start GPaste daemon: `systemctl --user start org.gnome.GPaste.service`
4. Copy something not already in the history: `echo -n 99 | gpaste-client`
- Boom, history’s broken.

As you will see, the history is not randomly crafted:
- Already full.
- The oldest entry is by far the largest one and has a mime value attached (from my tests that means I copied it from ctrl+C; using gpaste-client does not seem to trigger the computation of this mime value).
- Said mime value is way larger in size than the total concatenation of all 100 entries as pure text.

This last point is the most important one. Indeed while digging further I realized that when copying new stuff, thus discarding this last relatively huge entry, history size underflows. Expectedly, that leads to a loop that empties the history, trying to get back to a more realistic size than ~UINT64_MAX. As observed, copying new entries hardly help, since the history size won’t get recomputed until the daemon is restarted (which in itself should not be an issue if the underflow had not happened in the first place).

Now as to why the history size underflows, it very much seems like the history size is computed as the sum of pure-text length of all entries in the history, while every entry size is computed as the total size the entry “weighs” in the history.xml file, meaning the length of the text itself + the length of the mime text-html value.

For what it’s worth, the underflow append in gpaste-history.c::g_paste_history_private_check_size, at the only step this for loop seems to take:
```c
for (GList *_history = history; _history; _history = g_list_next (_history))
            priv->size -= g_paste_item_get_size (_history->data);
```
No definite idea what to fix though.

**Comment by Keruspe** [comment] 2023-04-20 12:15
Thanks a lot for this deep analysis!

We're now à the third (?) issue behind this symptom.

I'll give it a look soon

**Comment by bobi32** [comment] 2023-04-20 13:16
You’re welcome!

Pretty sure my first diagnosis was wrong, I would count that as a second issue.

Down the line what was really necessary was to find a keep track of past changes on the history *file*.
Once done (hint: incron + local git repository), it was just a matter of identifying the breaking change, get the history before & after, and at last replay the change a bit until a plausible cause is found rather than guessed.

Anyway, if the use case I came up with turns out not as reproducible as expected, here’s the configuration I run gpaste with:
```bash
$ dconf dump /org/gnome/GPaste/
[/]
history-name='history'
max-memory-usage=uint64 5
track-changes=true
track-extension-state=true
```
For the rest I must be sticking to defaults I guess.

**Comment by galvani** [comment] 2023-04-26 14:24
> > 
> 
> Hello! For several weeks this command line `gpaste-client daemon-reexec` helps me to restart the GPaste. But I am annoyed of it, how can I make my GPaste work forever?

yeah, and you cannot find this line in gpaste, right?! ;-)

**Comment by axelsimon** [comment] 2023-09-26 09:59
I'm still hitting this error regularly. On Fedora 38. And I've just `gpaste-client daemon-reexec`ed to no avail.

Can we reopen, @Keruspe ? This is sadly clearly not fixed :disappointed:

**Comment by Keruspe** [comment] 2023-09-26 10:58
Which version of GPaste are you running ? It was fixed in 44.1

**Comment by rbjorklin** [comment] 2023-09-27 04:54
I was about to chime in and agree with @axelsimon but as it turns out 44.1 hasn't landed in Fedora 38 yet unless you enable the updates-testing repo.

This worked for me: `dnf upgrade --enablerepo=updates-testing gnome-shell-extension-gpaste gpaste gpaste-ui`

**Comment by axelsimon** [comment] 2023-09-27 10:04
Thanks @rbjorklin, I'm now on 44.1 using your tip. Looking forward to _not_ seeing this bug anymore :wink:

**Comment by Keruspe** [comment] 2023-09-27 11:24
We'll definitely open it back if you hit it again, but pretty confident @bobi32 fix was the proper one

**Comment by dumbasPL** [comment] 2023-09-27 11:26
> pretty confident @bobi32 fix was the proper one

Yeah, ever since 44.1 I haven't experienced a single problem related to this.
