### ISSUE TITLE
loss of text formatting

### ISSUE THREAD

**Issue by mattia-b89** [Keruspe/GPaste#203] opened 2017-03-25 15:11 UTC
when you select a previous copied item from the list,
it has no formatting

e.g.
I copy the bold and italic text **_ciao_**
now, if I paste it into libreoffice, I get **_ciao_**
I copy a new text selection **_bye_**
now, if I paste it into libreoffice, I get **_bye_**
I select the text "ciao" from the item history
now, if I paste it into libreoffice, I get "ciao" (no italic nor bold)

**Comment by Keruspe** [comment] 2017-04-03 13:41
Hi,

What kind of formatting is it? (e.g. what application are you copying from ?)

This is related to #176

**Comment by Keruspe** [comment] 2017-04-07 15:25
Once 3.24 is out and you can try it, please tell me if the problem still persists.
If so we'll see which mime type needs to be handled, it's pretty straightforward to add one now.

**Comment by Keruspe** [comment] 2017-04-11 15:37
Looks like they use html from a quick grep in their sources, thus closing.

If you're able to reproduce with GPaste 3.24, please reopen.

**Closed by Keruspe** 2017-04-11 15:37 UTC
Labels: BUG

**Comment by mattia-b89** [comment] 2017-04-11 16:54
Yes, I'm (was) waiting for 3.24 in official Arch repo (since 3.24 needs gnome 3.24, and Arch team usually waits until first maintenance update 3.24.1 in this case).
I will update (re-open) this bug report, if it will be still valid.

The copy "source" is from the LibreOffice's Writer application.
