### ISSUE TITLE
gnome-shell extension doesn't always detect that Ctrl is down

### ISSUE THREAD

**Issue by afn** [Keruspe/GPaste#220] opened 2017-09-15 14:58 UTC
Having the gnome-shell extension only show the index when Ctrl is held down is a useful feature, but it doesn't detect if the Ctrl key is down initially.

With the default keybindings, you can press `<Ctrl><Alt>H`, release the `<Alt>` and `H` keys while still holding `<Ctrl>`, and enter an index number. But in this flow, the indexes aren't visible because there's no `key-press-event` received for the `<Ctrl>` key. It's already down by the time the menu starts listening for events.

Is there a way in Clutter to poll the keyboard to determine what keys are *currently* down? That would be the ideal solution.

If not, then we could have the daemon convey to the extension whether or not the triggering keypress included the ctrl key:

1. Change `src/gnome-shell/indicator.js` to get the ctrl state from the `show-history` event and use that to determine the initial index visibility (rather than always resetting it to `false`).
1. Change the signature of `g_paste_daemon_show_history()` to take an additional boolean parameter indicating the state of the ctrl key, and pass this parameter along to the `show-history` event.
1. Change g_paste_show_history_keybinding_show_history to call `g_paste_keybinding_get_modifiers()`, determine if the mask includes Ctrl, and pass the ctrl state to `g_paste_daemon_show_history()`.

Thoughts? I'm happy to implement the above in a pull request, but I'd first like to find out if the extension can simply poll for the ctrl-key state, as this would be significantly simpler and would eliminate the need for the daemon to be aware of the significance of the ctrl key.

Thanks!

**Comment by Keruspe** [comment] 2018-03-07 14:34
I think this should be fixed directly in the extension itself. Not sure how though.
I'm not a bug fan of passing this data through the signal

**Comment by Keruspe** [comment] 2018-03-11 22:01
We now always refresh the state on each key release event, so this should be at least way better detected, closing as I don't see any way of improving it further

**Closed** 2018-03-11 22:02 UTC
Labels: BUG
