### ISSUE TITLE
GPaste pastes old copy.

### ISSUE THREAD

**Issue by vyasgiridhar** [Keruspe/GPaste#182] opened 2016-11-11 12:59 UTC
GPaste pastes the old copies from the history even though the recent copy is present in the history.
This is sometimes solved by restarting the daemon but sometimes it doesn't work.

**Comment by Keruspe** [comment] 2016-12-12 16:01
Which version of GPaste do you use?
Is your primary selection synced with your clipboard?
Does your primary selection affect your hisotry?

**Comment by vyasgiridhar** [comment] 2016-12-12 16:55
I think the problem is localized to pasting in the terminal from the browser.
The content does appears in the gpaste history.

**Comment by vyasgiridhar** [comment] 2016-12-12 17:46
I am currently using GPaste 3.22.0

**Comment by Keruspe** [comment] 2016-12-13 09:37
Is your primary selection synced with your clipboard?
Does your primary selection affect your hisotry?
(In the settings)

**Comment by vyasgiridhar** [comment] 2016-12-13 09:45
No.

The setting is switched off.

**Comment by cesarizu** [comment] 2016-12-13 09:54
I have the same issue from time to time. I've tried changing some of the settings but nothing works for me other than restarting the gpaste daemon. I'm using openSUSE tumbleweed and these are the versions of the packages I have installed:
```
gnome-shell-extension-gpaste-3.20.4-3.1.noarch
gpaste-3.20.4-3.1.x86_64
gpaste-lang-3.20.4-3.1.noarch
libgpaste6-3.20.4-3.1.x86_64
typelib-1_0-GPaste-1_0-3.20.4-3.1.x86_64
```
> Is your primary selection synced with your clipboard?

No

> Does your primary selection affect your history?

No

**Comment by Keruspe** [comment] 2016-12-13 10:23
Debug logs could be useful in that case.
kill the running gpaste-daemon and run it with G_MESSAGES_DEBUG=all in the env

Are you running on x11 or wayland?

**Comment by cesarizu** [comment] 2016-12-13 12:51
x11... I'll start the daemon like that and see if the problem happens again and post some logs here.

**Comment by Keruspe** [comment] 2016-12-13 15:04
Logs are printed to stderr, so it depends on your distribution

**Comment by cesarizu** [comment] 2016-12-15 23:23
I've run this on an open terminal with G_MESSAGES_DEBUG=all for a couple days straight but unfortunately I didn't have any copy/paste problems during this time. I'll try to keep running like that to see if I can reproduce this anymore.

**Comment by vyasgiridhar** [comment] 2016-12-16 02:08
Try copying from chrome to a terminal. The issue should appear after some time.
I don't have access to my computer for a few days so I will try to get the log in a few days.

**Comment by cesarizu** [comment] 2016-12-16 09:32
It finally happened. These are the last lines from the log:

```
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: owner change
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: set text
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: owner change
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: owner change
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:28792): GPaste-DEBUG: history: add
(gpaste-daemon:28792): GPaste-DEBUG: item: set state: 0
(gpaste-daemon:28792): GPaste-DEBUG: item: set state: 1
(gpaste-daemon:28792): GPaste-DEBUG: history: update
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: notify finish
(gpaste-daemon:28792): GPaste-DEBUG: history: remove '0'
(gpaste-daemon:28792): GPaste-DEBUG: item: set state: 1
(gpaste-daemon:28792): GPaste-DEBUG: history: selected
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: select
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: select item
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: select text
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: set text
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: store
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: select text
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: store
(gpaste-daemon:28792): GPaste-DEBUG: history: update
(gpaste-daemon:28792): GPaste-DEBUG: history: select '1'
(gpaste-daemon:28792): GPaste-DEBUG: history: add
(gpaste-daemon:28792): GPaste-DEBUG: history: selected
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: select
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: select item
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:28792): GPaste-DEBUG: history: select '1'
(gpaste-daemon:28792): GPaste-DEBUG: history: add
(gpaste-daemon:28792): GPaste-DEBUG: history: selected
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: select
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: select item
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:28792): GPaste-DEBUG: history: select '2'
(gpaste-daemon:28792): GPaste-DEBUG: history: add
(gpaste-daemon:28792): GPaste-DEBUG: item: set state: 0
(gpaste-daemon:28792): GPaste-DEBUG: item: set state: 1
(gpaste-daemon:28792): GPaste-DEBUG: history: update
(gpaste-daemon:28792): GPaste-DEBUG: history: selected
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: select
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: select item
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: select text
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: set text
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: store
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: select item
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: select text
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: set text
(gpaste-daemon:28792): GPaste-DEBUG: CLIPBOARD: store
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: owner change
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: notify
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: targets ready
(gpaste-daemon:28792): GPaste-DEBUG: PRIMARY: set text
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: text ready
(gpaste-daemon:28792): GPaste-DEBUG: clipboards-manager: notify finish
```

The state right now is that what gets pasted is not present on the gpaste list. If I select the top entry from the gpaste list, it gets highlighted but it doesn't do anything at all, I still get the other string pasted.

I'm trying to reproduce the problem but it's not consistent. One thing that I noticed is that I accidentally pressed ctrl-alt-v instead of ctrl-shift-v. I tried this again after restarting the daemon and it blocked gpaste maybe once in 20 tries, so I'm not positive this is what causes the problem.

**Comment by mock** [comment] 2017-01-03 20:10
having similar problems with the failure to paste into the terminal what's actively chosen in the gpaste history. i'm running fedora 25 with gnome 3.22.2 and wayland. packages installed:

gpaste-libs-3.22.1-1.fc25.x86_64
gnome-shell-extension-gpaste-3.22.1-1.fc25.noarch
gpaste-ui-3.22.1-1.fc25.x86_64
gpaste-3.22.1-1.fc25.x86_64

i've tried restarting the gpaste-daemon several times. i've unset and reset all my clipboard syncing, which are enabled as my normal settings. i've toggled the tracking as well. nothing works except restarting my gnome session.

i am not finding anything the logs causing the problem.

i just tried closing all my terminal sessions and restarting, and that seemed to correct the problem. does that make it a gnome-terminal issue?

**Comment by mock** [comment] 2017-01-27 18:32
i'm guessing no progress has been made on this issue. i have now gotten to the point where closing my terminal windows and restarting gpaste services does not fix/reset behavior. i am guessing wayland won't be something i can use until these matters clear up. there is no other good clipboard tool which seems to work outside of X.

**Comment by Keruspe** [comment] 2017-01-30 20:10
Hi,

No progress on this yet as I didn't get the time I wish I had to work on GPaste lately.
I should be able to work on it properly in february and hopefully fix this asap.

**Comment by Keruspe** [comment] 2017-02-13 13:27
I have some big rework of clipboards interactions wrt #176 
I'll see if this one is still relevant and fix it once I'm done with it.

**Comment by Keruspe** [comment] 2017-02-13 16:04
@cesarizu that log really seems weird, what GPaste version is this?

**Comment by Keruspe** [comment] 2017-02-13 16:05
@mock can you reproduce easily? what needs to be done in which order to reproduce?

**Comment by rbjorklin** [comment] 2017-10-30 13:17
I'm seeing this issue with Fedora 26 and these packages:

    gnome-shell-extension-gpaste-3.24.3-1.fc26.noarch
    gpaste-libs-3.24.3-1.fc26.x86_64
    gpaste-ui-3.24.3-1.fc26.x86_64
    gpaste-3.24.3-1.fc26.x86_64

For me I've only noticed this behavior when using Slack and when it starts happening it doesn't stop.

**Comment by mattia-b89** [comment] 2018-02-11 18:05
I cannot reproduce it on Arch Linux x86_64 with gnome and gpaste 3.26

**Comment by vyasgiridhar** [comment] 2018-02-13 10:59
I think this has been solved. @Keruspe, you can close this if you want.

**Closed** 2018-02-13 16:04 UTC
Labels: BUG
